"""add created_at to pedidos

Revision ID: 180026238f15
Revises: 20250816_merge_heads
Create Date: 2025-08-18 21:44:34.569510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180026238f15'
down_revision: Union[str, Sequence[str], None] = '20250816_merge_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('created_at', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_taxa_entrega_id'), 'taxa_entrega', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxa_entrega_id'), table_name='taxa_entrega')
    op.alter_column('pedidos', 'tipo_entrega',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('pedidos', 'forma_pagamento',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('pedidos', 'created_at')
    # ### end Alembic commands ###
