"""add troco to pedidos

Revision ID: 2fc06e8b4e4d
Revises: ef057836003b
Create Date: 2025-09-10 15:12:34.120249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fc06e8b4e4d'
down_revision: Union[str, Sequence[str], None] = 'ef057836003b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('troco', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'troco')
    # ### end Alembic commands ###
