"""add fcm_token to usuarios

Revision ID: b59776570855
Revises: 2fc06e8b4e4d
Create Date: 2025-09-10 16:03:56.179699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59776570855'
down_revision: Union[str, Sequence[str], None] = '2fc06e8b4e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('fcm_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fcm_token')
    # ### end Alembic commands ###
